name: GOOL BOT Scanner

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scanner:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        working-directory: gool_bot
        run: |
          pip install -r requirements.txt


      - name: Run GOOL BOT
        working-directory: gool_bot
        env:
          INFERSPORTS_API_KEY: ${{ secrets.INFERSPORTS_API_KEY }}
          HIGHLIGHTLY_API_KEY: ${{ secrets.HIGHLIGHTLY_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          python main.py
